spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nota
    driver-class-name: org.postgresql.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: false
logging:
  level:
    com.limecoding.api: INFO